#!/usr/bin/env python3
"""Scan pattern frontmatter and regenerate ``DESIGN_PATTERNS.md``.

Dependencies live in a pattern's own frontmatter, so co-location keeps one
source of truth. This script reads that frontmatter and writes the lookup
index. The index is generated and never hand-edited: run the router after any
pattern change, and `--check` asserts the file on disk is current.

A broken pattern stops the write. An index built from frontmatter nobody has
checked would route a call to a pattern that cannot resolve, and the failure
would surface one milestone later inside a subagent.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import common  # noqa: E402

HEADER = """# Design patterns

Generated by `tools/router.py` from the frontmatter of every pattern under
`patterns/`. Never edit this file by hand. Run the router after any pattern
change.

A pattern is addressed by its `id`. `/generate` and `/update` take that id, and
`resolve_deps.py` reads the same frontmatter to build the bundle.
"""

CELLS_NOTE = """## Cells

The nine cell files are guidance, not routed patterns. A writer opens exactly
one, selected by a `cell:<TYPE>_<WEIGHT>` dependency, and never carries the
other eight.
"""


def plural(count: int) -> str:
    return f"{count} pattern" + ("" if count == 1 else "s")


def sort_key(pattern: common.Pattern) -> tuple[int, int, str]:
    target = common.PATTERN_TARGETS.index(pattern.target) \
        if pattern.target in common.PATTERN_TARGETS else len(common.PATTERN_TARGETS)
    phase = common.PATTERN_PHASES.index(pattern.phase) \
        if pattern.phase in common.PATTERN_PHASES else len(common.PATTERN_PHASES)
    return target, phase, pattern.id


def _cell(text: str) -> str:
    return text.replace("|", "\\|") if text else "none"


def render(root: Path, patterns: list[common.Pattern]) -> str:
    lines = [HEADER, "## Index", ""]
    if patterns:
        lines += [
            "| Target | Phase | Pattern | Writes | Dependencies | File |",
            "| :--- | :--- | :--- | :--- | :--- | :--- |",
        ]
        for pattern in sorted(patterns, key=sort_key):
            lines.append(
                f"| {pattern.target} | {pattern.phase} | `{pattern.id}` "
                f"| {_cell(', '.join(pattern.writes))} "
                f"| {_cell(', '.join(f'`{dep}`' for dep in pattern.dependencies))} "
                f"| `{pattern.relpath}` |"
            )
    else:
        lines.append("No patterns yet.")

    lines += ["", CELLS_NOTE, "| Cell | File | Written |", "| :--- | :--- | :--- |"]
    weights = common.load_weights(root)
    for region_type in weights["region_types"]:
        for weight in weights["location_weights"]:
            name = f"{region_type}_{weight}"
            path = Path(common.CELLS_DIR) / f"{name}.md"
            written = "yes" if (root / path).exists() else "no"
            lines.append(f"| `{name}` | `{path}` | {written} |")

    return "\n".join(lines) + "\n"


def collect(root: Path) -> tuple[list[common.Pattern], list[str]]:
    """Every pattern, and every reason the index cannot be written."""
    patterns, read_errors = common.load_patterns(root)
    problems = [f"{path.relative_to(root)}: {message}" for path, message in read_errors]

    seen: dict[str, common.Pattern] = {}
    for pattern in patterns:
        for problem in common.pattern_errors(pattern, root):
            problems.append(f"{pattern.relpath}: {problem}")
        first = seen.get(pattern.id)
        if first is not None:
            problems.append(
                f"{pattern.relpath}: id {pattern.id!r} is already used by {first.relpath}"
            )
        else:
            seen[pattern.id] = pattern

    return patterns, problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--root", type=Path, default=common.REPO_ROOT)
    parser.add_argument("--check", action="store_true",
                        help="fail if the index on disk is not what the patterns imply")
    args = parser.parse_args(argv)
    root = args.root.resolve()

    try:
        patterns, problems = collect(root)
    except common.DocError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1

    index = render(root, patterns)
    path = root / common.ROUTER_PATH

    if args.check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != index:
            print(f"error: {common.ROUTER_PATH} is stale. Run python tools/router.py.",
                  file=sys.stderr)
            return 1
        print(f"{common.ROUTER_PATH} is current: {plural(len(patterns))}.")
        return 0

    path.write_text(index, encoding="utf-8")
    print(f"wrote {common.ROUTER_PATH}: {plural(len(patterns))}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
